"""Small built-in fluorophore library for probe concept generation."""

FLUOROPHORES: dict[str, dict[str, object]] = {
    "coumarin": {
        "excitation_nm": "320-420",
        "emission_nm": "400-520",
        "brightness": 0.65,
        "photostability": 0.60,
        "water_compatibility": 0.55,
        "synthetic_accessibility": 0.75,
        "common_linkers": ["amide", "alkyl", "carbamate"],
        "mechanisms": ["ICT", "PET", "turn-on fluorescence"],
    },
    "fluorescein": {
        "excitation_nm": "480-500",
        "emission_nm": "510-540",
        "brightness": 0.90,
        "photostability": 0.65,
        "water_compatibility": 0.85,
        "synthetic_accessibility": 0.70,
        "common_linkers": ["amide", "thiourea", "ester"],
        "mechanisms": ["PET", "turn-on fluorescence", "ratiometric response"],
    },
    "rhodamine": {
        "excitation_nm": "520-560",
        "emission_nm": "560-620",
        "brightness": 0.90,
        "photostability": 0.80,
        "water_compatibility": 0.65,
        "synthetic_accessibility": 0.60,
        "common_linkers": ["amide", "hydrazide", "spirolactam"],
        "mechanisms": ["turn-on fluorescence", "FRET", "ratiometric response"],
    },
    "BODIPY": {
        "excitation_nm": "480-530",
        "emission_nm": "500-580",
        "brightness": 0.85,
        "photostability": 0.85,
        "water_compatibility": 0.35,
        "synthetic_accessibility": 0.55,
        "common_linkers": ["alkyne", "aryl", "amide"],
        "mechanisms": ["PET", "FRET", "turn-off fluorescence"],
    },
    "naphthalimide": {
        "excitation_nm": "360-460",
        "emission_nm": "450-570",
        "brightness": 0.70,
        "photostability": 0.75,
        "water_compatibility": 0.55,
        "synthetic_accessibility": 0.70,
        "common_linkers": ["imide N-substitution", "alkyl", "amide"],
        "mechanisms": ["ICT", "PET", "ratiometric response"],
    },
    "cyanine": {
        "excitation_nm": "600-800",
        "emission_nm": "650-850",
        "brightness": 0.75,
        "photostability": 0.45,
        "water_compatibility": 0.70,
        "synthetic_accessibility": 0.45,
        "common_linkers": ["alkyl", "sulfonate", "amide"],
        "mechanisms": ["aggregation-induced emission", "turn-on fluorescence"],
    },
    "dansyl": {
        "excitation_nm": "330-380",
        "emission_nm": "470-560",
        "brightness": 0.55,
        "photostability": 0.55,
        "water_compatibility": 0.40,
        "synthetic_accessibility": 0.85,
        "common_linkers": ["sulfonamide", "amide"],
        "mechanisms": ["ICT", "turn-on fluorescence"],
    },
    "pyrene": {
        "excitation_nm": "320-350",
        "emission_nm": "370-480",
        "brightness": 0.65,
        "photostability": 0.80,
        "water_compatibility": 0.25,
        "synthetic_accessibility": 0.60,
        "common_linkers": ["alkyl", "amide", "triazole"],
        "mechanisms": ["excimer", "turn-off fluorescence", "aggregation-induced emission"],
    },
}
