"""Simple dependency-light HTML report generation."""

from __future__ import annotations

from html import escape

from azai.reports.markdown import generate_markdown_report


def markdown_report_to_html(markdown_text: str) -> str:
    """Convert the constrained AZAI Markdown report format to a standalone HTML document.

    This is intentionally small and dependency-light. It handles headings, bullets,
    fenced-ish plain paragraphs, and simple Markdown tables generated by AZAI.
    """
    body: list[str] = []
    lines = markdown_text.splitlines()
    in_table = False
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_table:
                body.append("</tbody></table>")
                in_table = False
            continue
        if stripped.startswith("# "):
            body.append(f"<h1>{escape(stripped[2:])}</h1>")
        elif stripped.startswith("## "):
            if in_table:
                body.append("</tbody></table>")
                in_table = False
            body.append(f"<h2>{escape(stripped[3:])}</h2>")
        elif stripped.startswith("- "):
            body.append(f"<p class='bullet'>• {escape(stripped[2:])}</p>")
        elif stripped.startswith("|") and stripped.endswith("|"):
            cells = [escape(cell.strip()) for cell in stripped.strip("|").split("|")]
            if all(set(cell) <= {"-", ":", " "} for cell in cells):
                continue
            if not in_table:
                body.append("<table><tbody>")
                in_table = True
            tag = "th" if not any("<tr>" in item for item in body[-2:]) else "td"
            body.append("<tr>" + "".join(f"<{tag}>{cell}</{tag}>" for cell in cells) + "</tr>")
        else:
            body.append(f"<p>{escape(stripped)}</p>")
    if in_table:
        body.append("</tbody></table>")
    return """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AZAI Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2.5rem; color: #242633; }
    h1 { font-size: 2rem; margin-bottom: 0.3rem; }
    h2 { margin-top: 1.8rem; border-bottom: 1px solid #ddd; padding-bottom: 0.25rem; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.92rem; }
    th, td { border: 1px solid #ddd; padding: 0.45rem 0.6rem; text-align: left; }
    th { background: #f6f7fb; }
    .bullet { margin-left: 1rem; }
  </style>
</head>
<body>
""" + "\n".join(body) + "\n</body>\n</html>\n"


def molecule_report_html(smiles: str, title: str = "AZAI Molecular Intelligence Report") -> str:
    """Create a standalone HTML report for a molecule."""
    return markdown_report_to_html(generate_markdown_report(smiles, title=title))
